#!/usr/bin/env python3
"""Build independently installable Codex and Antigravity handoff bundles."""

from __future__ import annotations

import argparse
import shutil
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills" / "handoff"
GENERATED_MARKER = ".handoff-bundles-generated"


def _copy_skill(source: Path, destination: Path, include_agents: bool) -> None:
    ignored_names = ["__pycache__", "*.pyc", "*.pyo"]
    if not include_agents:
        ignored_names.append("agents")
    ignored = shutil.ignore_patterns(*ignored_names)
    shutil.copytree(source, destination, symlinks=False, ignore=ignored)


def build_bundles(output_root: Path) -> None:
    if output_root.exists() and not (output_root / GENERATED_MARKER).is_file():
        raise RuntimeError(
            f"refusing to replace unmarked output directory: {output_root}"
        )

    output_root.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="handoff-bundles-", dir=output_root.parent
    ) as temporary_directory:
        staged_root = Path(temporary_directory) / "bundles"
        _copy_skill(SOURCE, staged_root / "codex" / "handoff", include_agents=True)
        _copy_skill(
            SOURCE,
            staged_root / "antigravity" / "handoff",
            include_agents=False,
        )
        (staged_root / GENERATED_MARKER).write_text(
            "Generated by scripts/build_bundles.py.\n", encoding="utf-8"
        )
        if output_root.exists():
            shutil.rmtree(output_root)
        shutil.move(staged_root, output_root)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--authorized", action="store_true")
    parser.add_argument("--output-root", type=Path, default=ROOT / "bundles")
    args = parser.parse_args()
    if not args.authorized:
        parser.error("bundle writes require --authorized")
    build_bundles(args.output_root.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
